version: '2'
services:
  # Notice how the service name, container name and repo directory (where the Dockerfile lives) all match.
  # As this is a ruby acceptance tests app, it is not designed to run always, just ad hoc commands to run the tests.
  # No log redirect, no port, no restart policy.
  applitools-holiday-hackathon:
    container_name: applitools-holiday-hackathon
    build: ./applitools-holiday-hackathon

    volumes:
      # Our convention is to always map the app files to /src within the container
      - ./applitools-holiday-hackathon:/src
